### ISSUE TITLE
Acronyms are not available

### ISSUE THREAD

**Issue by tomzx** [Sommerregen/grav-data-smileys-emoji#1]
If I put the following in my content file, the following gets outputted. I'd expect that all smileys would be converted into their image equivalent, but it is not the case.

```
:+1:
:heart:
:smile:

:-) :D :'-( <3
```

![image](https://cloud.githubusercontent.com/assets/188960/8509573/05f0cd74-2278-11e5-8ca6-89eb7422ab71.png)

**Comment by Sommerregen** [comment]
Dear @tomzx,

the acronyms you can use highly depends on the smileys package you are using. This one here doesn't convert acronyms like :-), :D etc. to their iconographic representation. You can see the full list here http://www.emoji-cheat-sheet.com/ .

However you can assign acronyms to images by adding to the the [`emoji.yaml`](https://github.com/Sommerregen/grav-data-smileys-emoji/blob/master/emoji.yaml) the following lines

``` yaml
smileys:
  smile:
    enabled: true
    acronyms: ":) :-)"
    description: "smile"
```

and any acronym ":-)" should be converted now. To get a grasp of the configuration options, you can peek into the [Pidgins configurations file](https://github.com/Sommerregen/grav-data-smileys-pidgin-smileys/blob/master/pidgin_smileys.yaml).

**Comment by tomzx** [comment]
@Sommerregen Alright, then maybe the README.md needs to be updated (or I don't understand the formulation of the following sentences) to better reflect the fact that no acronyms are defined by default other than the smiley name itself?

> You can then use any of the below smiley acronyms in your pages and `Grav Smileys Plugin` will automatically convert them to their icon graphic file equivalent. As an example
> 
> ```
> I love you <3
> ```
> 
> will then transform to
> 
> <code>I love you :heart:</code>

**Comment by Sommerregen** [comment]
Oh, you are right. I will change it. Thank you!

**Comment by Sommerregen** [comment]
Fixed with current release!
